name: Lint, Build, Release

on: [push, pull_request]

defaults:
  run:
    working-directory: reagurk

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run Linter
        run: yarn eslint --ignore-path .gitignore .
        
      - name: Build Site
        run: yarn build
        
      - name: Gzip Build
        run: tar -zcvf reagurk.tar.gz build

      - name: Create Release
#         if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.ref_name }}-${{ github.run_id }}
    
      - name: Upload Release Asset
#         if: github.ref == 'refs/heads/main'
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: reagurk.tar.gz
          asset_name: reagurk.tar.gz
          asset_content_type: application/gzip
